### ISSUE TITLE
Error in full template

### ISSUE THREAD

**Issue by kylebutts** [grantmcdermott/quarto-revealjs-clean#9]
Opening issue from a commit comment. Error when rendering: `quarto use template grantmcdermott/quarto-revealjs-clean-demo`

```
Quitting from lines 295-302 [etable] (temp.qmd)
Error in `path.expand()`:
! invalid 'path' argument
Backtrace:
 1. fixest::etable(mods, highlight = .(se = "complaints"), arraystretch = 1.5)
 2. fixest:::path_to_relative(path)
 3. base::normalizePath(x, "/", mustWork = FALSE)
 4. base::path.expand(path)
Execution halted
```

**Comment by grantmcdermott** [comment]
Ugh, looks like recent Quarto (or maybe fixest?) update broke this.

Haven't had time to debug properly, but the problem seems to be with `setFixest_etable(markdown = TRUE)` [here](https://github.com/grantmcdermott/quarto-revealjs-clean-demo/blob/ce2cc5d17d6f7444e546e248e7e11588a0ab6207/template.qmd#L295). Removing that line allows the slide deck to render properly, although this particular slide/table looks rubbish now.

**Comment by grantmcdermott** [comment]
Scratch that: I spoke too soon. I have a new version of R and had not updated `pdftools`. Installing this, and other dependencies [as per the instructions](https://github.com/grantmcdermott/quarto-revealjs-clean-demo/blob/ce2cc5d17d6f7444e546e248e7e11588a0ab6207/template.qmd#L42-L68) in the slide deck, leads to everything rendering fine.
